#!/bin/sh -e

## Remove build directory
##rm -rf ../public_html/clientV2

## temporary UV_THREADPOOL_SIZE hack for node-sass
## see https://github.com/jtangelder/sass-loader/issues/100
UV_THREADPOOL_SIZE=100 NODE_ENV=development NODE_PATH=. ./node_modules/.bin/babel-node ./node_modules/.bin/webpack --progress --colors
##set UV_THREADPOOL_SIZE=100; set NODE_ENV=development; set NODE_PATH=.; ./node_modules/.bin/babel-node .\node_modules\webpack\bin\webpack.js --progress --colors
